@TodoListAPI_HostAddress = http://localhost:5266

GET {{TodoListAPI_HostAddress}}/weatherforecast/
Accept: application/json
###
POST {{TodoListAPI_HostAddress}}/AddTodo/
Accept: application/json
{
  "task":"TEST TASK"
}
###
